AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  SampleLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      FunctionName: cicd_testing_by_ahmad
      Handler: index.handler
      Runtime: nodejs14.x
